// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultiLineDebugExpressionEvaluator
{
    internal sealed partial class Vsix
    {
        public const string Id = "MultiLineDebugExpressionEvaluator.fba8eada-353a-44c2-8ef9-9143a2301fd3";
        public const string Name = "MultiLine Debug Expression Evaluator";
        public const string Description = @"Visual Studio extension for quick watch window which allows to debug and edit multilines expressions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lsoft";
        public const string Tags = "visualstudio";
    }
}
