// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace MultiLineDebugExpressionEvaluator
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MultiLineDebugExpressionEvaluatorString = "bce096f2-8da0-4034-8e16-85cdbd8773d0";
        public static Guid MultiLineDebugExpressionEvaluator = new Guid(MultiLineDebugExpressionEvaluatorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}